config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'calculators#calculator'
  post 'calculate',               to: 'calculators#calculate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculation.rb
class Calculation

  NUMBER_MATCHER        = /^\d*(\.\d*)?$/

  class InvalidNumberError        < Exceptions::ApplicationError; end
  class UnsupportedOperationError < Exceptions::ApplicationError; end

  ##
  # Constructor.
  # Takes two numbers and an operation to be performed on the numbers.

  def initialize( input_a, input_b, operation )
    unless input_a =~ NUMBER_MATCHER && input_b =~ NUMBER_MATCHER
      raise InvalidNumberError, "Inputs must be numbers."
    end

    @input_a    = input_a.to_f
    @input_b    = input_b.to_f
    @operation  = operation
  end

  ##
  # Return the result of this calculation.

  def result
    return case @operation
      when '+'    then @input_a + @input_b
      when '-'    then @input_a - @input_b
      when '*'    then @input_a * @input_b
      when '/'    then @input_a / @input_b
      when '**'   then @input_a ** @input_b
      when 'sqrt' then Math.sqrt( @input_a )
        
      else raise UnsupportedOperationError, "Unsupported operation."
    end
  end

  ##
  # Return the string representation of this calculation.

  def as_string
    return case @operation
      when '+'    then "#{@input_a} + #{@input_b} = #{result}"
      when '-'    then "#{@input_a} - #{@input_b} = #{result}"
      when '*'    then "#{@input_a} * #{@input_b} = #{result}"
      when '/'    then "#{@input_a} / #{@input_b} = #{result}"
      when '**'   then "#{@input_a} ** #{@input_b} = #{result}"
      when 'sqrt' then "sqrt( #{@input_a} ) = #{result}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController

  def calculator
  end

  def calculate
    calculation = Calculation.new(
      params[:input_a],
      params[:input_b],
      params[:operation] )

    result = calculation.result
    update_history( calculation )

    render json: { result: result, history: session[:history] }
  end

  private

    ##
    # Update the calculation history that is persisted in the session.
    # Takes the calculation to add to the history.

    def update_history( calculation )
      history = session[:history] ? session[:history] : []
      history.push( calculation.as_string )
      session[:history] = history.last( 10 )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculators/calculator.slim
div.col-md-8.col-md-offset-2

  = form_tag( calculate_path, method: 'post', id: 'calculator' )
    = hidden_field_tag 'operation'

    div.col-md-4.container
      = label_tag 'input_a', 'A',   class: 'col-md-1'
      = number_field_tag 'input_a', class: 'col-md-3'

    div.col-md-4.container
      = label_tag 'input_b', 'B',   class: 'col-md-1'
      = number_field_tag 'input_b', class: 'col-md-3'

    div.col-md-4.container.result-container
      div.col-md-7
        label Result
      div#result.col-md-3


  div.row.col-md-8.col-md-offset-2
    button#add.submit value='+'
      | +
    button#subtract.submit value='-'
      | -
    button#multiply.submit value='*'
      | *
    button#divide.submit value='/'
      | /
    button#exponentiate.submit value='**'
      | **
    button#sqrt.submit value='sqrt'
      | sqrt

  div.row.col-md-8.col-md-offset-2
    span NOTE: The sqrt function only operates on input A.

  hr.col-md-12

  div.row.col-md-10.col-md-offset-1
    h4 History
    ul#history
      - if session[:history]
        - session[:history].reverse.each do |value|
          li
            span = value

app/views/calculators/new.slim
= form_tag( calculate_path, method: 'post', id: 'calculator' )

  div
    = label_tag 'input_a', 'Input A'
    = number_field_tag 'input_a'

  div
    = label_tag 'input_b', 'Input B'
    = number_field_tag 'input_b'

  = hidden_field_tag 'operation'

div
  button#add.submit value='+'
    | +
  button#subtract.submit value='-'
    | -
  button#multiply.submit value='*'
    | *
  button#divide.submit value='/'
    | /
  button#exponentiate.submit value='**'
    | **
  button#sqrt.submit value='sqrt'
    | sqrt

h4 Result
span#result

h4 History
ul#history
  - if session[:history]
    - session[:history].reverse.each do |value|
      li
        span = value

app/views/layouts/_header.slim
div#header.container
  h1 Calc-U-Lately
  h3
    em The Latest in Calculation

app/views/layouts/application.slim
doctype html
html
  head
    title Calc-U-Lately
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'layouts/header'

    div#main.container
      = yield